version: '3'
services:
    php-apache:
        image: php:7.2.12-apache
        container_name: oxygen_updater_backend
        build:
            context: ./
            dockerfile: Dockerfile-development
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html:z
        links:
            - 'mariadb'
        environment:
            # This is a *DEVELOPER* environment. These values are not the same values of the currently hosted environments

            # Database access
            DATABASE_HOST: "mariadb"
            DATABASE_USER: "root"
            DATABASE_PASS: "test1234"
            DATABASE_NAME: "oxygen_updater"

            # Server timezone for use in PHP scripts
            TIMEZONE: "Europe/Amsterdam"

            # Discord webhook settings
            SUBMITTED_UPDATE_FILE_WEBHOOK_ACTION_URL: "http://localhost:8000/"
            SUBMITTED_UPDATE_FILE_WEBHOOK_AUTHOR_NAME: "Oxygen Updater Developer"
            SUBMITTED_UPDATE_FILE_WEBHOOK_URL: "https://discordapp.com/api/webhooks/test/some.webhook.key"

            MISSING_UPDATE_VERSIONS_WEBHOOK_ACTION_URL: "http://localhost:8000/"
            MISSING_UPDATE_VERSIONS_WEBHOOK_AUTHOR_NAME: "Oxygen Updater Developer"
            MISSING_UPDATE_VERSIONS_WEBHOOK_URL: "https://discordapp.com/api/webhooks/test/some.other.webhook.key"

            # News image uploader (usable for Admins with a valid login to the Admin Portal)
            # Path where the news images are stored on Disk
            NEWS_IMAGES_PATH: "./img/news"
            # Relative URL where the news images are accessible on the domain.
            NEWS_IMAGES_RELATIVE_URL: "./img/news"
            # Authentication service URL. This is part of the Admin Portal, which is not open source.
            # Set $use_in_memory_auth in news-images.php to true to use / work on the news images uploader
            NEWS_IMAGE_UPLOADER_AUTH_URL: ""

            # XDebug: Add your own IP to the remote_host of XDebug if you want to debug PHP (e.g. using PHPStorm).
            # Docker Toolbox: type docker-machine ip to get the IP to use here.
            # Docker for Mac / Linux Docker / Docker for Windows: set to localhost?
            XDEBUG_CONFIG: remote_host=192.168.99.1
    composer:
      restart: 'no'
      image: composer:1.7.3
      command: bash -c "composer update; chmod -R 777 /app/vendor"
      volumes:
       - ./:/app

    mariadb:
        image: mariadb:10.2
        container_name: oxygen_updater_database
        volumes:
            - mariadb:/var/lib/mysql
            - ./database.sql:/docker-entrypoint-initdb.d/dump.sql
        ports:
            - 3306:3306
        environment:
            TZ: "Europe/Amsterdam"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "test1234"
            MYSQL_USER: 'oxygen-updater'
            MYSQL_PASSWORD: 'be-the-first-to-update'
            MYSQL_DATABASE: 'oxygen_updater'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: oxygen_updater_phpmyadmin
        links:
            - mariadb
        ports:
            - 8183:80
        environment:
            PMA_HOST: mariadb
            PMA_USER: root
            PMA_PASSWORD: test1234
            PMA_ARBITRARY: 1
volumes:
    mariadb:
